
-- Add more varied bot responses for better conversation coverage
INSERT INTO bot_library (trigger_keywords, response_text, coping_tip_title, coping_tip_content, risk_level) VALUES
('fear, afraid, scared, phobia, panic, terrified', 'Fear is a natural response that''s meant to protect us, but sometimes it can feel overwhelming. What you''re experiencing is valid, and you''re not alone in feeling this way. Would you like to talk about what''s making you feel afraid?', 'Fear-Setting Exercise', 'Write down your fear, then list: 1) What''s the worst that could happen? 2) How likely is it? 3) What would you do if it happened? This helps make fears more manageable.', 'Medium'),

('confident, confidence, self-esteem, worth, value, doubt', 'Self-doubt can be really challenging, but recognizing it is the first step. You have inherent worth that doesn''t depend on external achievements. What situations tend to make you question yourself most?', 'Confidence Building', 'Keep a ''wins'' journal. Each day, write down 3 things you did well, no matter how small. This trains your brain to notice your strengths and achievements.', 'Low'),

('change, transition, moving, new, different, uncertain', 'Change can feel unsettling, even when it''s positive. It''s normal to feel uncertain during transitions. Your feelings about this change are completely valid. What aspect of this change feels most challenging right now?', 'Change Navigation', 'Focus on what you can control in this transition. Make a list of things within your influence vs. things outside of it. Channel your energy toward what you can affect.', 'Low'),

('guilt, guilty, shame, regret, mistake, wrong, bad', 'Guilt and shame can be heavy burdens to carry. It''s important to remember that making mistakes is part of being human. What you did doesn''t define who you are. Would you like to talk about what''s weighing on you?', 'Self-Forgiveness Practice', 'Ask yourself: What would I tell a friend in this situation? Treat yourself with the same compassion. Acknowledge the mistake, learn from it, and take one small step toward making amends if needed.', 'High'),

('perfectionist, perfect, control, standards, failure, achieve', 'Perfectionism often comes from a place of caring deeply, but it can become exhausting. You don''t have to be perfect to be worthy of love and respect. What areas of your life feel most affected by these high standards?', 'Good Enough Practice', 'Set a timer for 80% of the time you''d normally spend on a task, then stop. This helps you experience that ''good enough'' often truly is good enough.', 'Medium'),

('future, worry, anxious, what if, uncertain, plan', 'Worrying about the future is so common - our minds are designed to anticipate problems. But when worry takes over, it can rob us of the present moment. What specific future scenarios are concerning you most?', 'Future Focus Technique', 'Use the 10-10-10 rule: Will this matter in 10 minutes? 10 months? 10 years? This helps put worries in perspective and focus on what truly matters.', 'Medium'),

('social, socially, people, crowd, judgment, embarrassed', 'Social situations can feel overwhelming sometimes. Many people experience social anxiety - you''re definitely not alone in this. Your comfort zone is valid, and we can work on expanding it at your own pace. What social situations feel most challenging?', 'Social Confidence Builder', 'Start small: Make eye contact and smile at one person today. Ask one question in conversation. These tiny steps build social confidence over time.', 'Medium'),

('motivation, motivated, lazy, procrastination, energy, drive', 'Low motivation can be frustrating, especially when you have things you want or need to do. Sometimes our minds and bodies are asking for rest or a different approach. What usually helps you feel more energized?', 'Motivation Spark', 'Use the 2-minute rule: If something takes less than 2 minutes, do it now. For bigger tasks, commit to just 2 minutes. Often, starting is the hardest part.', 'Low'),

('money, financial, finances, debt, job, career, income', 'Financial stress can affect every area of our lives. It''s completely understandable to feel worried about money - these are real, practical concerns. What aspect of your financial situation feels most pressing right now?', 'Financial Anxiety Relief', 'Write down one small financial action you can take today - even checking your account balance counts. Small steps toward financial awareness reduce anxiety.', 'Medium'),

('body, appearance, weight, looks, ugly, fat, skinny', 'Our relationship with our bodies can be complex and deeply personal. The way you feel about yourself matters, and these concerns are valid. What thoughts about your body are bothering you most?', 'Body Appreciation', 'Each morning, thank your body for 3 things it does for you (breathing, walking, healing, etc.). This shifts focus from appearance to function and gratitude.', 'High'),

('habit, addiction, substance, drinking, smoking, drugs', 'Recognizing patterns that aren''t serving you takes real courage. Whether it''s a habit you want to change or something more serious, acknowledging it is an important first step. What would feel most helpful to talk about?', 'Habit Change Strategy', 'Identify your trigger (when/where/why the habit happens), then plan a replacement behavior. Make the good choice easier and the unwanted habit harder.', 'High'),

('purpose, meaning, direction, lost, why, point', 'Questioning life''s meaning and your purpose is actually a sign of growth and self-awareness. These big questions can feel overwhelming, but they''re also opportunities for discovery. What areas of your life feel most unclear right now?', 'Purpose Exploration', 'Think about moments when you felt most alive and engaged. What were you doing? Who were you with? These clues can point toward your values and purpose.', 'Medium'),

('trauma, past, hurt, abuse, violence, memories', 'Thank you for trusting me with something so personal and difficult. Trauma can have lasting effects, and healing isn''t linear. Your feelings and experiences are valid. Please consider reaching out to a mental health professional who specializes in trauma.', 'Grounding for Trauma', 'If you feel overwhelmed, focus on your physical environment: Feel your feet on the ground, notice 5 things you can see, take slow breaths. You are safe in this moment.', 'High'),

('help, support, therapy, counselor, therapist, professional', 'Seeking help is a sign of strength, not weakness. Professional support can provide tools and perspectives that make a real difference. What''s making you consider additional support right now?', 'Finding Help', 'Psychology Today has a therapist finder tool. Many therapists offer sliding scale fees. Your college/workplace may have counseling services. You deserve support.', 'Medium');
